name: ${project.artifactId}
version: ${project.version}
api-version: "1.13"
author: denmeh
main: com.github.unldenis.corpse.CorpsePlugin
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
commands:
  spawncorpse:
  removecorpse: